### ISSUE TITLE
ISIC 训练代码

### ISSUE THREAD

**Issue by fffacc** [iam-nacl/DTMFormer#1]
您好！请问您是否方便提供在ISIC数据集上的训练代码呢？非常感谢！

**Comment by iam-nacl** [comment]
感谢您对我们工作的关注和支持，如果您希望在ISIC数据集上进行训练，我们推荐您以现有的 `train.py` 脚本为基础进行调整。主要需要修改的部分是
(1)classes
```
parser.add_argument('--classes', type=int, default=2, help='number of classes')
```
(2)evaluate
```
#  ----------------------------------- evaluate -----------------------------------
    val_loss = 0
    dices = 0
    hds = 0
    smooth = 1e-25
    mdices, mhds = np.zeros(args.classes), np.zeros(args.classes)
    flag = np.zeros(600)  # record the patients

    model.eval()  # (set in evaluation mode, this affects BatchNorm and dropout)
    batch_losses = []

    current_time = time.time()
    for batch_idx, (imgs, mask, *rest) in enumerate(valloader):
        if isinstance(rest[0][0], str):
            image_filename = rest[0][0]
        else:
            image_filename = '%s.png' % str(batch_idx + 1).zfill(3)
        imgs = Variable(imgs.to(device='cuda'))
        mask = Variable(mask.to(device='cuda'))

        with torch.no_grad():
            outputs,_ = model(imgs)
        
        outputs = F.softmax(outputs, dim=1)
        loss = loss_fn(outputs, mask)
        val_loss = loss.data.cpu().numpy()

        gt = mask.detach().cpu().numpy()
        pred = outputs.detach().cpu().numpy()  # (b, c,h, w) tep
        seg = np.argmax(pred, axis=1)  # (b, h, w) whether exist same score?

        patientid = int(image_filename[:3])
        if flag[patientid] == 0:
            if np.sum(flag) > 0:  # compute the former result
                b, s, h, w = seg_patient.shape
                for i in range(1, args.classes):
                    pred_i = np.zeros((b, s, h, w))
                    pred_i[seg_patient == i] = 1
                    gt_i = np.zeros((b, s, h, w))
                    gt_i[gt_patient == i] = 1
                    mdices[i] += metrics.dice_coefficient(pred_i, gt_i)
                    del pred_i, gt_i
            seg_patient = seg[:, None, :, :]
            gt_patient = gt[:, None, :, :]
            flag[patientid] = 1
        else:
            seg_patient = np.concatenate((seg_patient, seg[:, None, :, :]), axis=1)
            gt_patient = np.concatenate((gt_patient, gt[:, None, :, :]), axis=1)
        # ---------------the last patient--------------
    b, s, h, w = seg_patient.shape
    for i in range(1, args.classes):
        pred_i = np.zeros((b, s, h, w))
        pred_i[seg_patient == i] = 1
        gt_i = np.zeros((b, s, h, w))
        gt_i[gt_patient == i] = 1
        mdices[i] += metrics.dice_coefficient(pred_i, gt_i)
        del pred_i, gt_i
    patients = np.sum(flag)
    mdices = mdices / patients
    for i in range(1, args.classes):
        dices += mdices[i]
```

**Comment by fffacc** [comment]
> 感谢您对我们工作的关注和支持，如果您希望在ISIC数据集上进行训练，我们推荐您以现有的 `train.py` 脚本为基础进行调整。主要需要修改的部分是 (1)classes
> 
> ```
> parser.add_argument('--classes', type=int, default=2, help='number of classes')
> ```
> 
> (2)evaluate
> 
> ```
> #  ----------------------------------- evaluate -----------------------------------
>     val_loss = 0
>     dices = 0
>     hds = 0
>     smooth = 1e-25
>     mdices, mhds = np.zeros(args.classes), np.zeros(args.classes)
>     flag = np.zeros(600)  # record the patients
> 
>     model.eval()  # (set in evaluation mode, this affects BatchNorm and dropout)
>     batch_losses = []
> 
>     current_time = time.time()
>     for batch_idx, (imgs, mask, *rest) in enumerate(valloader):
>         if isinstance(rest[0][0], str):
>             image_filename = rest[0][0]
>         else:
>             image_filename = '%s.png' % str(batch_idx + 1).zfill(3)
>         imgs = Variable(imgs.to(device='cuda'))
>         mask = Variable(mask.to(device='cuda'))
> 
>         with torch.no_grad():
>             outputs,_ = model(imgs)
>         
>         outputs = F.softmax(outputs, dim=1)
>         loss = loss_fn(outputs, mask)
>         val_loss = loss.data.cpu().numpy()
> 
>         gt = mask.detach().cpu().numpy()
>         pred = outputs.detach().cpu().numpy()  # (b, c,h, w) tep
>         seg = np.argmax(pred, axis=1)  # (b, h, w) whether exist same score?
> 
>         patientid = int(image_filename[:3])
>         if flag[patientid] == 0:
>             if np.sum(flag) > 0:  # compute the former result
>                 b, s, h, w = seg_patient.shape
>                 for i in range(1, args.classes):
>                     pred_i = np.zeros((b, s, h, w))
>                     pred_i[seg_patient == i] = 1
>                     gt_i = np.zeros((b, s, h, w))
>                     gt_i[gt_patient == i] = 1
>                     mdices[i] += metrics.dice_coefficient(pred_i, gt_i)
>                     del pred_i, gt_i
>             seg_patient = seg[:, None, :, :]
>             gt_patient = gt[:, None, :, :]
>             flag[patientid] = 1
>         else:
>             seg_patient = np.concatenate((seg_patient, seg[:, None, :, :]), axis=1)
>             gt_patient = np.concatenate((gt_patient, gt[:, None, :, :]), axis=1)
>         # ---------------the last patient--------------
>     b, s, h, w = seg_patient.shape
>     for i in range(1, args.classes):
>         pred_i = np.zeros((b, s, h, w))
>         pred_i[seg_patient == i] = 1
>         gt_i = np.zeros((b, s, h, w))
>         gt_i[gt_patient == i] = 1
>         mdices[i] += metrics.dice_coefficient(pred_i, gt_i)
>         del pred_i, gt_i
>     patients = np.sum(flag)
>     mdices = mdices / patients
>     for i in range(1, args.classes):
>         dices += mdices[i]
> ```

非常感谢您的回答！请问您在对ISIC划分训练集和测试集时，是按图片顺序划分还是随机打乱划分的呢？

**Comment by iam-nacl** [comment]
为了能和前人工作进行对比，我们采用的数据划分与论文The Lighter the Better: Rethinking Transformers in Medical Image Segmentation Through Adaptive Pruning(TMI2023)保持一致，采用随机划分的方式（因为当时官网没有开放测试集）。但据我的了解，前段时间ISIC官网似乎更新了测试集，如果您要做新的工作，我更建议您使用官网更新的最新的数据划分

**Comment by fffacc** [comment]
> 为了能和前人工作进行对比，我们采用的数据划分与论文The Lighter the Better: Rethinking Transformers in Medical Image Segmentation Through Adaptive Pruning(TMI2023)保持一致，采用随机划分的方式（因为当时官网没有开放测试集）。但据我的了解，前段时间ISIC官网似乎更新了测试集，如果您要做新的工作，我更建议您使用官网更新的最新的数据划分

好滴！非常感谢您的建议！我会参考您的意见，再次感谢您的帮助！
