### ISSUE TITLE
ACDC数据集格式

### ISSUE THREAD

**Issue by xiaogege1210** [iam-nacl/DTMFormer#2]
您好，请问您在使用ACDC数据集的时候，是将它放在"./dataset/ACDC"路径下的吗，我在训练的时候他总是报错，我看官方给的数据集里好像也没有MainPatient/trainofficial.txt这个文件，请问您能提供一下您所使用的数据集吗，十分感谢您
![A_4HI$FJQ )V RRW$TGMR1Q](https://github.com/user-attachments/assets/fb658c1e-db6c-4352-9fea-91b719c46f57)

**Comment by iam-nacl** [comment]
您好，感谢对我们工作的关注。由于ACDC是3D的数据集，而我们的工作是基于2D分割网络的，所以我们实际使用的数据不是原始的nii格式数据，而是经过切片化处理的png格式数据，因此如果您直接使用官方数据集会存在问题。
切片级ACDC数据及可以从下面链接获取[ACDC](https://drive.google.com/file/d/18W_d8ho0Tl7TgPQXczOXZK5OUxtYkQdc/view?usp=sharing)
需要注意，代码中涉及到的trainofficial.txt是依据官方数据划分对png格式数据进行的划分，详情如下。
[testofficial.txt](https://github.com/user-attachments/files/17823795/testofficial.txt)
[trainofficial.txt](https://github.com/user-attachments/files/17823796/trainofficial.txt)
[valofficial.txt](https://github.com/user-attachments/files/17823799/valofficial.txt)

**Comment by xiaogege1210** [comment]
十分感谢您的帮助，现在我已经能够对ACDC数据集进行训练和测试了，但是还有一个问题想请教一下您，我在测试完成后并没有看到保存的图片，请问您在论文中展示的ACDC数据集可视化图片是怎么得到的

**Comment by iam-nacl** [comment]
您好，我们的代码在正常的训练和测试阶段并未进行可视化的操作。不过我可以附上相关代码供你参考，当您需要用到可视化的时候可以根据您的需要进行插入与修改。
```
import cv2
img_ori = cv2.imread(os.path.join(args.dataset + '/img', image_filename))
img = np.zeros((h, w, 3))
img_r = img_ori[:, :, 0]
img_g = img_ori[:, :, 1]
img_b = img_ori[:, :, 2]
table = np.array([[193, 182, 255], [219, 112, 147], [237, 149, 100], [211, 85, 186], [204, 209, 72],
                  [144, 255, 144], [0, 215, 255], [96, 164, 244], [128, 128, 240], [250, 206, 135]])
seg0 = seg[0, :, :] # 绘制分割结果
# seg0 = gt[0, :, :]  # 绘制label

for i in range(1, args.classes):
    img_r[seg0 == i] = table[i - 1, 0]
    img_g[seg0 == i] = table[i - 1, 1]
    img_b[seg0 == i] = table[i - 1, 2]

img[:, :, 0] = img_r
img[:, :, 1] = img_g
img[:, :, 2] = img_b
img = np.uint8(img)
# '''
# img = np.uint8(seg[0, :, :] * 255)

dice_pic = np.zeros(args.classes)
for i in range(1, args.classes):
    pred_i = np.zeros((b, h, w))
    pred_i[seg == i] = 255
    gt_i = np.zeros((b, h, w))
    gt_i[gt == i] = 255
    dice_pic[i] = metrics.dice_coefficient(pred_i, gt_i)
dice = dice_pic.sum() / (args.classes - 1)
num = "%06d" % utils.globalvar.CNT

fulldir = args.direc + "/"
if not os.path.isdir(fulldir):
    os.makedirs(fulldir)
image_filename = num + '_' + image_filename.replace('.png', '') + '_' + str(dice) + '.png'
cv2.imwrite(fulldir + image_filename, img)

```

**Comment by xiaogege1210** [comment]
十分感谢您的帮助！
