### ISSUE TITLE
预训练模型

### ISSUE THREAD

**Issue by yongchangxu** [iam-nacl/DTMFormer#3]
你好，我想请问一下Setr_DTMFormer在训练时使用了预训练模型吗，我将你们的这个模型用来训练Synapse数据集但是效果并不是太好，平均Dice分数不到70，想问一下你们有使用它训练Synapse数据集嘛，效果如何

**Comment by iam-nacl** [comment]
感谢对我们工作的关注，我们曾尝试过对腹部多器官数据集BTCV的2D切片进行分割，Setr_DTMFormer最优dice同样只有70多，我认为你的结果可能的原因有下面几个：
（1）2D分割方法在腹部多器官数据集下的弱表现：在2024年MICCAI、TMI等顶刊顶会的最新方法无一例外是3D分割方法，并且3D sota与2D sota 逐渐拉开了越来越大的差距
（2）Setr网络本身的弱表现：Setr网络没有针对医学图像的设计，在各项医学数据集上的表现都称不上优秀，尤其是在腹部多器官这类较困难的数据集上
（3）DTMFormer的收敛性：由于涉及更复杂的运算，DTMFormer对于参数的要求比普通Transformer 更苛刻一些（稀疏率、学习率、其它超参），可以尝试尝试不同参数
（4）数据集预处理：我们将BTCV的图片都统一处理256*256的2D切片，以便用于2D网络的分割

**Comment by yongchangxu** [comment]
好的，十分感谢您的耐心解答
