### ISSUE TITLE
三通道图像分割

### ISSUE THREAD

**Issue by waner1998** [iam-nacl/DTMFormer#4]
作者您好，感谢您精彩的工作。
我想用您的模型作为对比模型(三通道医疗图像分割，二分类)，但是从您的文章中看到，您针对不同的数据集设置了不同的学习率，想请教您，学习率以及batchsize的设置，在我的任务中有什么建议吗，谢谢。

Sincerely,

**Comment by iam-nacl** [comment]
您好，感谢您对我们工作的关注。在我们的工作中，确实对不同的数据集设置了不同的参数，这是由于DTMFormer对于小规模医学数据集存在一定的收敛困难问题，通过调整合适的参数可以解决这个问题。由于不同的数据集收敛难度、基础模型不同，直接套用其它超参数可能意义不大，我可以和您分享一些我个人的调参习惯：
1、学习率的设置：假设基础网络在1e-4下收敛正常，你可以以此为基础尝试附近学习率的收敛表现，比如5e-4、1e-4、5e-5，观察收敛偏向学习率更大/更小方向进行更精细的学习率选择。
2、batchsize的设置：在此方向我并未有过多的调整经验，受限与算力资源，我习惯batchsize=4的设置，但这可能并非最佳。
3、其它超参数的设置：论文中式（4）的a值 、式（8）的加权值、式（11）的loss加权 这些参数和基础模型的选择关系较大，而式（5）的k值、DTMFormer的稀疏率 我认为和 数据集本身的冗余度关系较大，可以以我的设置为基准，尝试偏大/偏小带来的效果。
以上是我个人的一些调参经验，偏向于较为广泛的实验尝试，不一定是最优的方式，您可以略作参考

**Comment by waner1998** [comment]
> 您好，感谢您对我们工作的关注。在我们的工作中，确实对不同的数据集设置了不同的参数，这是由于DTMFormer对于小规模医学数据集存在一定的收敛困难问题，通过调整合适的参数可以解决这个问题。由于不同的数据集收敛难度、基础模型不同，直接套用其它超参数可能意义不大，我可以和您分享一些我个人的调参习惯： 1、学习率的设置：假设基础网络在1e-4下收敛正常，你可以以此为基础尝试附近学习率的收敛表现，比如5e-4、1e-4、5e-5，观察收敛偏向学习率更大/更小方向进行更精细的学习率选择。 2、batchsize的设置：在此方向我并未有过多的调整经验，受限与算力资源，我习惯batchsize=4的设置，但这可能并非最佳。 3、其它超参数的设置：论文中式（4）的a值 、式（8）的加权值、式（11）的loss加权 这些参数和基础模型的选择关系较大，而式（5）的k值、DTMFormer的稀疏率 我认为和 数据集本身的冗余度关系较大，可以以我的设置为基准，尝试偏大/偏小带来的效果。 以上是我个人的一些调参经验，偏向于较为广泛的实验尝试，不一定是最优的方式，您可以略作参考

谢谢您的建议。我在复现代码的时候，发现loss函数一直报错Traceback (most recent call last):
  File "F:\seg\seg\run_train.py", line 193, in <module>
    main(args, i+1)
  File "F:\seg\seg\run_train.py", line 186, in main
    train_main(model, net_type, train_image_path, train_mask_path, image_size, batchsize, lr, args.epochs, save_path, args.gpu_choose, args.num_workers)
  File "F:\seg\seg\libs\train.py", line 260, in train_main
    loss.backward()
  File "C:\Users\user\.conda\envs\torch\lib\site-packages\torch\_tensor.py", line 525, in backward
    torch.autograd.backward(
  File "C:\Users\user\.conda\envs\torch\lib\site-packages\torch\autograd\__init__.py", line 267, in backward
    _engine_run_backward(
  File "C:\Users\user\.conda\envs\torch\lib\site-packages\torch\autograd\graph.py", line 744, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR。您的loss函数非常复杂，有没有不挑设备的loss函数？我换掉loss函数就可以正常运行，用原代码的loss就无法运行，问题应该是出在您代码的loss函数中

**Comment by iam-nacl** [comment]
我们采用的loss其实比较简单，分别是loss_fn = DC_and_CE_loss()和loss_SmoothL1 = nn.SmoothL1Loss()，即DE_CE Loss和SmoothL1 Loss，这两种都是很常见的Loss种类，网上对这两种Loss都有很多实现方法，您可以选择使用匹配自己环境的代码Loss，原理一致即可
